"""empty message

Revision ID: 1006b0b5a0fd
Revises: 61453abe2c1f
Create Date: 2021-02-24 17:04:41.622220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1006b0b5a0fd'
down_revision = '61453abe2c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_column('users', 'raul')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('raul', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
