"""empty message

Revision ID: 3145daa25fef
Revises: aaebc1a66463
Create Date: 2021-02-24 14:16:08.882135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3145daa25fef'
down_revision = 'aaebc1a66463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('raul', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'raul')
    # ### end Alembic commands ###
